savethegrain/posts/urls.py
from django.urls import path
from .views import (
    ForDonorsListView,
    PostCreateView,
    DonationsListView,
    about, 
    home
)

app_name = 'posts'

urlpatterns = [
    path('',home, name = 'main-home'),
    path('post/new/',PostCreateView.as_view(template_name=""), name = 'donation-create'),
    path('about/',about, name = 'main-about'),
    path('dashboard/',DonationsListView.as_view(template_name="posts/dashboard.html"), name="ngo-dashboard"),
    path('donordashboard/<str:username>',ForDonorsListView.as_view(template_name="posts/donorDash.html"), name="donor-dashboard"),    

]

savethegrain/savethegrain/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('donations/', include('posts.urls')),
    path('signup/', include('useraccounts.urls')),
]

savethegrain/useraccounts/urls.py
from django.urls import path
from .views import (
    signup
)

app_name = 'useraccounts'

urlpatterns = [
    path('',signup,name="signup"),
]

savethegrain/posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class post(models.Model):
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=500)
    pub_date = models.DateTimeField(default=timezone.now)
    Donor = models.ForeignKey(User, on_delete=models.CASCADE)
    food_quantity = models.PositiveIntegerField(default=0)
    # NGO = models.OneToOneField(User,default="NULL")

    # def get_absolute_url(self):
    #     return reverse('blog:post-detail', kwargs={'pk':self.pk})
    

savethegrain/useraccounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.
class STGUserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('DNR','Donor'),
        ('NGO', 'NGO'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    user_type = models.CharField(max_length=3, choices=USER_TYPE_CHOICES)
    Location = models.TextField(max_length=60)
    Pincode = models.PositiveIntegerField()

savethegrain/posts/forms.py
from django import forms
from .models import post


class PostCreateForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        "placeholder":"Info",
        "rows":10,
        "cols":40
    }))
    title = forms.CharField(widget=forms.Textarea(attrs={
        "placeholder":"iTitle",
        'style':'resize:none;',
        'cols':40,
        'rows':1
    }))
    class Meta:
        model = post
        fields = ["title","content"]

savethegrain/useraccounts/forms.py
from django import forms  
from .models import STGUserProfile
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm

USER_TYPE_CHOICES = (
        ('DNR','Donor'),
        ('NGO', 'NGO'),
    )


class STGUserRegister(UserCreationForm):

    email = forms.EmailField(required = False, widget= forms.EmailInput(attrs={'placeholder':'(Not Required)'}))
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {
            'password1': _('nothing'),
        }

class ProfileCreationForm(forms.ModelForm):
    user_type = forms.CharField(widget=forms.Select(choices=USER_TYPE_CHOICES) )
    Location = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 30}))
    class Meta:
        model = STGUserProfile
        fields = ['user_type','Location','Pincode']        

savethegrain/posts/views.py
from django.http.response import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render,get_object_or_404
from django.http import HttpRequest
from django.views.generic import (
    ListView,
    CreateView,
)
from django.contrib.auth.models import User
from .models import post
from .forms import PostCreateForm

# Create your views here.

class DonationsListView(ListView):
    model =  post 
    template_name = 'posts/base.html'
    context_object_name = "posts"
    #ordering = ["-pub_date"]

    def get_query_set(self):
        return post.objects.filter(user_type="donor")

class ForDonorsListView(ListView):
    model =  post 
    template_name = 'posts/donorDash.html'
    context_object_name = "posts"
    #ordering = ["-pub_date"]
    
    def get_query_set(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return post.objects.filter(Donor=user).order_by('-pub_date')      

class PostCreateView(LoginRequiredMixin,CreateView):
    model =  post
    form_class = PostCreateForm

    def form_valid(self, form):
            form.instance.author = self.request.user
            return super().form_valid(form)    


def about(response):
    return HttpResponse("<h1>About</h1>")

def home(response):
    return render(response,'posts/base.html',{})

savethegrain/useraccounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import ProfileCreationForm, STGUserRegister
def signup(request):
    if request.method == 'POST':
        u_form = STGUserRegister(request.POST)
        p_form = ProfileCreationForm(request.POST)
        if u_form.is_valid and p_form.is_valid:
            u_form.save()
            username = u_form.cleaned_data.get('username')
            raw_password = u_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            user = u_form.save()
            profile = p_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            if profile.user_type == "NGO":
                return redirect('posts:ngo-dashboard')
            else :
                return redirect('posts:donor-dashboard')    
    else:
        u_form = STGUserRegister()
        p_form = ProfileCreationForm()
    return render(request, 'useraccounts/signup.html', {'u_form': u_form,'p_form':p_form})

savethegrain/posts/templates/posts/donor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="./donor.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

</head>
<body>
    <div class="container-md">
        <div class="jumbotron pb-4">
            <h1 class="display-4">Hello, Joker!</h1>
            <p class="lead">Your previous donations are listed below</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-secondary" href="#" role="button">Donate Now</a>
        </div>
        <div class="d-flex flex-wrap">
            <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">01 November 2020</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Information</h6>
                  <p class="card-text">Lorem ipsum dolor sit amet</p>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Status : <span class="status red text-monospace">NOT CLAIMED</span></h6>
                  <p class="card-text">
                      To  <br>
                      Name : <br>
                      Phone : <br>
                      Address : <br>
                  </p>  
                </div>
              </div>
              <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">01 November 2020</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Information</h6>
                  <p class="card-text">Lorem ipsum dolor sit amet</p>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Status : <span class="status red text-monospace">NOT CLAIMED</span></h6>
                  <p class="card-text">
                      To  <br>
                      Name : <br>
                      Phone : <br>
                      Address : <br>
                  </p>  
                </div>
              </div>
              <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">01 November 2020</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Information</h6>
                  <p class="card-text">Lorem ipsum dolor sit amet</p>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Status : <span class="status red text-monospace">NOT CLAIMED</span></h6>
                  <p class="card-text">
                      To  <br>
                      Name : <br>
                      Phone : <br>
                      Address : <br>
                  </p>  
                </div>
              </div>
              <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">01 November 2020</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Information</h6>
                  <p class="card-text">Lorem ipsum dolor sit amet</p>
                  <h6 class="card-subtitle mb-2 text-muted">Donation Status : <span class="status red text-monospace">NOT CLAIMED</span></h6>
                  <p class="card-text">
                      To  <br>
                      Name : <br>
                      Phone : <br>
                      Address : <br>
                  </p>  
                </div>
              </div>
              
             
              
             <!-- {% for post in posts %} -->
      
      
        <!-- {% endfor %} -->
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>



</body>
</html>


savethegrain/posts/templates/posts/navbar.html
<header class="mb-auto fixed-top">
    <div>
        <h3 class="float-md-left mb-0">STG</h3>
        <nav class="nav nav-masthead justify-content-center float-md-right">
            <a class="nav-link active" aria-current="page" href="#">HOME</a>
            <a class="nav-link" href="#about">ABOUT US</a>
            <a class="nav-link" href="#contact">CONTACT US</a>
            <a class="nav-link" href="#">LOGIN</a>
            <a class="nav-link" href="{% url 'useraccounts:signup' %}">SIGNUP</a>
        </nav>
    </div>
</header>

savethegrain/posts/templates/posts/rec_after.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="./rec.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

</head>
<body>
    <div class="container-md">
        <div class="jumbotron pb-4">
            <h1 class="display-4">Hello, NGO1!</h1>
            <hr class="my-4">
            <p class="lead">Available Donations</p>

        </div>
                     <!-- {% for post in posts %} -->

        <div class="d-flex flex-wrap">
            <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Calicut Notebook</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 15 people
                      </strong>   
                      <br>
                      Address : Indian Express Building,<br> 
                                Banerji Rd, Kaloor,<br> 
                                Ernakulam,<br> 
                                Kerala 682017
                  </p>
                  <a class="btn btn-success" href="#" role="button">Claimed</a>
              </div>
           </div>
            <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Joseph Chettan’s</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 25 people
                      </strong>   
                      <br>
                      Address : Kadavanthara, Elamkulam,<br> 
                                Ernakulam,<br>
                                Kerala 682020
                  </p>
                  <a class="btn btn-secondary" href="#" role="button">Claim now</a>
              </div>
            </div>
              <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Grand Pavilion</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 20 people
                      </strong>   
                      <br>
                      Address : Express Building,<br> 
                                Kaloor,<br> 
                                Ernakulam,<br> 
                                Kerala 682017
                  </p>
                  <a class="btn btn-secondary" href="#" role="button">Claim now</a>
              </div>
        </div>
              
      
      
        <!-- {% endfor %} -->
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>



</body>
</html>


savethegrain/posts/templates/posts/rec_before.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="./rec.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

</head>
<body>
    <div class="container-md">
        <div class="jumbotron pb-4">
            <h1 class="display-4">Hello, NGO1!</h1>
            <hr class="my-4">
            <p class="lead">Available Donations</p>

        </div>
                     <!-- {% for post in posts %} -->

        <div class="d-flex flex-wrap">
            <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Calicut Notebook</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 15 people
                      </strong>   
                      <br>
                      Address : Indian Express Building,<br> 
                                Banerji Rd, Kaloor,<br> 
                                Ernakulam,<br> 
                                Kerala 682017
                  </p>
                  <a class="btn btn-secondary" href="#" role="button">Claim now</a>
              </div>
           </div>
            <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Joseph Chettan’s</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 25 people
                      </strong>   
                      <br>
                      Address : Kadavanthara, Elamkulam,<br> 
                                Ernakulam,<br>
                                Kerala 682020
                  </p>
                  <a class="btn btn-secondary" href="#" role="button">Claim now</a>
              </div>
            </div>
              <div class="card mr-5 mb-4" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Grand Pavilion</h5>
                  <h6 class="card-subtitle mb-2 text-muted">01 November 2020</h6>
                  <p class="card-text">
                      <strong>
                          Food for 20 people
                      </strong>   
                      <br>
                      Address : Express Building,<br> 
                                Kaloor,<br> 
                                Ernakulam,<br> 
                                Kerala 682017
                  </p>
                  <a class="btn btn-secondary" href="#" role="button">Claim now</a>
              </div>
        </div>
              
      
      
        <!-- {% endfor %} -->
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>



</body>
</html>


savethegrain/posts/templates/posts/style1.html
<style>
html{
    scroll-behavior: smooth;
}

body {
    height: 100vh;
    color: white    ;
    text-shadow: 0 0.05rem 0.1rem rgba(0, 0, 0, 0.5);
    box-shadow: inset 0 0 5rem rgba(0, 0, 0, 0.5);
    font-family: 'Montserrat', sans-serif;

    /* Change this color if u want */
    background: #232526;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, #414345, #232526);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, #414345, #232526); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    
}
.cover-container {
  background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),
  url("https://images.unsplash.com/photo-1475333154578-0538252118ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60://images.pexels.com/photos/226615/pexels-photo-226615.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500");
  background-size: cover;
  background-position: center;
}

.nav-link {
    padding: 0.25rem 0;
    color: rgba(255,255,255,0.5);
    margin-left: 1.5rem;
}


nav a {
    padding: 1rem 0;
    margin: 0 3rem;
    position: relative;
    letter-spacing: 2px;
}

.gotopbtn {
    position: fixed;
    width: 50px;
    height: 50px;
    background: #27ae60;
    bottom: 40px;
    right: 50px;

    text-decoration: none;
    text-align: center;
    line-height: 50px;
    color: white;
    font-size: 22px;
    border-radius: 100px;

}

nav a:last-child {
    margin-right: 0;
}

nav a::before,
nav a::after {
    content: '';
    position: absolute;
    width: 100%;
    height: 2px;
    background-color: white; /*Change the colour if needed*/
    left: 0;
    transform: scaleX(0);
    transition: all .5s;
}

nav a::before {
    top: 0;
    transform-origin: left;
}

nav a::after {
    bottom: 0;
    transform-origin: right;
}

nav a:hover::before,
nav a:hover::after {
    transform: scaleX(1);
}

.nav-link:hover{
    color: rgba(255,255,255,0.5);
    border-bottom-color:rgba(255,255,255,0.5);
}

.nav-link.active {
    color: white;
    border-bottom-color:white;

}

.btn-secondary, .btn-secondary:hover{
    color: #333;
    text-shadow: none;
}

#head{
    font-weight: 700;
    font-size: 3rem;
    margin : 310px 0 10px;
}


.service {
    margin: 75px 0;
    color: black;
}


.numbers .rect {
    position: relative;
    z-index: 1;
    box-shadow: 0 0 15px 1px rgba(166, 163, 223, 0.5);
    border-radius: 100px;
    width: 20rem;
    height: 12rem;
    padding-top: 4vmin;
    margin: 1rem;
}
  
.numbers {
    margin-top: -5vmin;
}
  
.numbers .rect h1 {
    font-size: 3em;    
}

.numbers .rect p {
    font-size: 1.2em;    
}


.section-1 {
    padding: 10vmin 0vmin;
  }
  
  .section-1 .row .col-md-6 .pray img {
    opacity: 0.8;
    width: 80%;
    border-radius: 0.2em;
  }
  
  .section-1 .row .col-md-6:last-child {
    position: relative;
  }
  
  .section-1 .row .col-md-6 .panel {
    position: absolute;
    top: 7vmin;
    left: -18vmin;
    background: white;
    border-radius: 3px;
    text-align: left;
    padding: 13vmin 5vmin 20vmin 10vmin;
    box-shadow: 0 0 15px 1px rgba(166, 163, 223, 0.5);
    font-family: var(--Rubik);
    z-index: 1;
  }
  
  .section-1 .row .col-md-6 .panel h1 {
    font-weight: bold;
    padding: 0.4em 0;
    font-size: 2em;
    color: black;
  }
  
  .section-1 .row .col-md-6 .panel p {
    font-size: 0.9em;
    color: rgba(0, 0, 0, 0.5);
  }



.title {
text-align: center;
font-weight: bold;
margin-bottom: 30px;
}
.subtitle {
text-align: center;
margin-bottom: 70px;
font-size: 18px;
}

.size {
width: 150px;
height: 150px;
}

.service-box {
padding: 0 35px;
margin-bottom: 10px;
text-align: center;
}


.service-box h2 {
margin-bottom: 40px;
font-weight: bold;
}

.service-box p {
font-size: 1.5rem;
color: #808080;
}

.fa-arrow-right {
font-size: 22px !important;
margin-top: 30px;
margin-bottom: 35px;
cursor: pointer;

}


.info {
margin: 200px 0;
color: black;
}

.info img {
max-width: 77%;
cursor: pointer;
}

.info h2 {
margin-top: 100px;
font-weight: bold;
line-height: 50px;
}

.info p {
margin-top: 25px;
margin-bottom: 50px;
color: #808080;
font-size: 14px;
line-height: 18px;
}

.info a {
width: 170px;
padding: 15px 10px;
display: block;
text-decoration: none !important;
color: #fff !important;
border-radius: 5px;
text-align: center;
font-weight: bold;
font-size: 14px;
box-shadow: 0 9px 9px 1px rgba(204, 204, 204, 0.5);
}


/*---review---*/
.review {
margin: 100px 0;
color: black;
}

.carousel-item img {
width: 150px;
border-radius: 50%;
}

.carousel-item {
text-align: center;
height: 430px;
}

.carousel-caption {
z-index: -1 !important;
box-shadow: 0 0 15px 1px rgba(166, 163, 223, 0.5);
border-radius: 5px;
margin-bottom: 50px;
}

.carousel-item h6 {
margin-top: 55px;
font-weight: bold;
color: #000 !important;
}

.carousel-item small {
margin-top: 10px;
margin-bottom: 50px;
display: block;
color: #000 !important;
}

.carousel-item p {
text-align: center;
padding: 0 50px;
font-size: 15px;
color: #808080 !important;
}

/* to separate image from text in mobile view*/
@media only screen and (max-width: 800px) {
.carousel-item 
{
    height: 520px;
}
.carousel-caption {
    margin: 0 10px 50px 10px;
    left: 0 !important;
    right: 0 !important;

}
}
/*---footer--*/

.footer{
    text-align: center;
    background: rgba(0, 0, 0, 0.74);
}

.footer h2 {
color: #fff;
font-weight: 600;
margin: 70px 0;
}

.footer input {
width: 60%;
background: transparent;
outline: none;
border: 0;
border-bottom: 1px solid #fff;
padding: 10px;
color: #fff;
margin-bottom: 30px;
text-align: center;
}

::placeholder {
color: #efefef;
font-size: 13px;
}

.footer button {
padding: 6px;
width: 180px;
margin: auto;
display: block;
color: #fff;
border: 1px solid #fff;
font-size: 20px;
background: transparent;
}

footer{
    background-color: #232323;
    position: absolute;
    width: 100%;
    height: 250px;
}

.footer-text{
    color: #54dcf2;
    opacity: 1;
    text-align: center;
    padding: 1rem;
    font-size: 18pt;
}

.footer-text h3 {
    font-size: 16pt;
  }

  
.icon{
    display: inline-block;
    padding: 2rem 5rem;
}
</style>